apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-volume
  namespace: portainer
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/portainer"

