apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/portainer"

