apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-consul-consul-server
  namespace: consul
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/consul/storage"

